<template>
  <div class="app-container">
    <div class="message">
      Do not edit this file unless you know what you are doing.
      <el-button type="primary" round @click="handleSaveConfig">Save</el-button>
    </div>
    <div class="editor-container">
      <json-editor ref="jsonEditor" v-model="value"></json-editor>
    </div>
  </div>
</template>

<script>
import JsonEditor from '@/components/JsonEditor'

export default {
  name: 'site-settings-advanced',
  components: { JsonEditor },
  data() {
    return {
      value: 'loading...'
    }
  },
  mounted() {
    this.$store.dispatch('GetSiteConfig', this.$store.getters.site_id).then(res => {
      this.value = JSON.parse(res)
    }).catch(error => {
      console.log(error)
    })
  },
  methods: {
    handleSaveConfig() {
      this.$store.dispatch('UpdateSiteConfig', { site_id: this.$store.getters.site_id, config: this.value }).then(res => {
        console.log(res)
      }).catch(error => {
        console.log(error)
      })
    }
  }
}
</script>
<style scoped>
  .editor-container{
    position: relative;
    height: 100%;
    font-family: "Source Sans Pro", "Helvetica Neue", Arial, sans-serif;
  }
  .message{
    background: #eef1f6;
    padding: 15px 16px;
    margin-bottom: 20px;
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: space-between;
  }
</style>
